### ISSUE TITLE
fails to require 'thor'

### ISSUE THREAD

**Issue by Habbie** [stevenchanin/itunes-playlist-to-usb#1]
On my system, even after sudo gem install bundle and sudo bundle install, I got errors when the script was trying to require thor.

Putting "require 'rubygems' " before the other requires fixed it for me. I have no idea if this is how things are supposed to work, but this worked for me :)

**Comment by paulhargreaves** [comment]
Instructions didn't state that a sugo gem install bundle was needed. Also, attempting to run Habble's sudo bundle install pops up a warning about running it as root. Might be worth adding to the 1st time instructions:
sudo gem install bundle
<above the>
bundle install

**Comment by stevenchanin** [comment]
Updated the README to reflect this issue. Thanks!
