### ISSUE TITLE
Error trying to process a valid file

### ISSUE THREAD

**Issue by paulhargreaves** [stevenchanin/itunes-playlist-to-usb#2]
** Error trying to process:
	K@#0%!: {"Track ID"=>6563, "Name"=>"K@#0%!", "Artist"=>"Korn", "Album"=>"Life Is Peachy", "Genre"=>"Metal", "Kind"=>"Matched AAC audio file", "Size"=>6810845, "Total Time"=>182560, "Track Number"=>8, "Year"=>1996, "Date Modified"=>#<DateTime: 2014-09-22T00:42:21+00:00 ((2456923j,2541s,0n),+0s,2299161j)>, "Date Added"=>#<DateTime: 2012-12-05T08:55:55+00:00 ((2456267j,32155s,0n),+0s,2299161j)>, "Bit Rate"=>256, "Sample Rate"=>44100, "Play Count"=>12, "Play Date"=>3490936497, "Play Date UTC"=>#<DateTime: 2014-08-15T08:34:57+00:00 ((2456885j,30897s,0n),+0s,2299161j)>, "Rating"=>100, "Normalization"=>2688, "Artwork Count"=>1, "Persistent ID"=>"5831C27B66869D35", "Track Type"=>"File", "Location"=>"file:///Users/paulhargreaves/Music/iTunes/iTunes%20Music/Korn/Life%20Is%20Peachy/08%20K@%230%25!.m4a", "File Folder Count"=>4, "Library Folder Count"=>1}

File does exist:
ocular:Life Is Peachy paulhargreaves$ ls 08\ K\@#0%\!.m4a 
08 K@#0%!.m4a
ocular:Life Is Peachy paulhargreaves$ pwd
//Users/paulhargreaves/Music/iTunes/iTunes Music/Korn/Life Is Peachy
ocular:Life Is Peachy paulhargreaves$ 

Putting file:///Users/paulhargreaves/Music/iTunes/iTunes%20Music/Korn/Life%20Is%20Peachy/08%20K@%230%25!.m4a into Firefox has it play the song.

**Comment by stevenchanin** [comment]
That file name was breaking string interpolation of the target file name. I juggled things around so I think it will work now. Can you pull and give it another try?

**Comment by paulhargreaves** [comment]
That error isn't occuring at the start of the copy and the files from that album have appeared on the USB stick.Thank you.
